"use client";

import { useState } from "react";
import { Plus, Minus } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "Is Zacky free to use?",
    answer:
      "Yes, we offer a generous free tier with daily generation limits. You can upgrade to Pro for unlimited access.",
  },
  {
    question: "How does the AI generation work?",
    answer:
      "We use advanced AI models to process your text prompts and generate high-quality content in seconds.",
  },
  {
    question: "Can I use the generated content commercially?",
    answer:
      "Yes! All content generated by Zacky is owned by you and can be used for commercial projects.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit cards and secure online payment methods via Stripe.",
  },
];

export default function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div id="faq" className="mx-auto max-w-4xl scroll-mt-24 px-10 pb-20">
      <div className="mb-16 space-y-4 text-center">
        <h2 className="text-4xl font-extrabold text-white md:text-5xl">
          Frequently Asked Questions
        </h2>
        <p className="text-muted-foreground mx-auto max-w-2xl text-sm font-light md:text-lg">
          Everything you need to know about our platform.
        </p>
      </div>

      <div className="space-y-4">
        {faqs.map((faq, index) => (
          <div
            key={index}
            className="group overflow-hidden rounded-2xl border border-white/5 bg-white/5 backdrop-blur-sm transition-all duration-300 hover:border-white/10"
          >
            <button
              onClick={() => setOpenIndex(openIndex === index ? null : index)}
              className="flex w-full items-center justify-between p-6 text-left"
            >
              <span className="group-hover:text-primary text-lg font-semibold text-white transition-colors">
                {faq.question}
              </span>
              {openIndex === index ? (
                <Minus className="text-primary h-5 w-5" />
              ) : (
                <Plus className="text-muted-foreground group-hover:text-primary h-5 w-5 transition-colors" />
              )}
            </button>
            <div
              className={cn(
                "overflow-hidden px-6 leading-relaxed text-gray-400 transition-all duration-500 ease-in-out",
                openIndex === index
                  ? "max-h-[200px] pb-6 opacity-100"
                  : "max-h-0 opacity-0",
              )}
            >
              {faq.answer}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
