"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "Is Zacky free to use?",
    answer:
      "Yes, we offer a generous free tier with daily generation limits. You can upgrade to Pro for unlimited access.",
  },
  {
    question: "How does the AI generation work?",
    answer:
      "We use advanced AI models to process your text prompts and generate high-quality content in seconds.",
  },
  {
    question: "Can I use the generated content commercially?",
    answer:
      "Yes! All content generated by Zacky is owned by you and can be used for commercial projects.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit cards and secure online payment methods via Stripe.",
  },
];

export default function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div id="faq" className="mx-auto max-w-4xl scroll-mt-20 px-10 pb-20">
      <h2 className="mb-12 text-center text-4xl font-extrabold text-white">
        Frequently Asked Questions
      </h2>
      <div className="space-y-4">
        {faqs.map((faq, index) => (
          <div
            key={index}
            className="bg-background/30 overflow-hidden rounded-lg border border-white/10 backdrop-blur-sm"
          >
            <button
              onClick={() => setOpenIndex(openIndex === index ? null : index)}
              className="flex w-full items-center justify-between p-4 text-left transition hover:bg-white/5"
            >
              <span className="font-semibold text-white">{faq.question}</span>
              {openIndex === index ? (
                <ChevronUp className="h-5 w-5 text-gray-400" />
              ) : (
                <ChevronDown className="h-5 w-5 text-gray-400" />
              )}
            </button>
            <div
              className={cn(
                "text-muted-foreground px-4 transition-all duration-300 ease-in-out",
                openIndex === index
                  ? "max-h-40 pb-4 opacity-100"
                  : "max-h-0 overflow-hidden opacity-0",
              )}
            >
              {faq.answer}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
